#!/bin/bash
set -eo pipefail

# Configurações
REPO="${GITHUB_REPO:-vittorpeli/portfolio}"
RALPH_DIR=".ralph"
ISSUE_FILE="$RALPH_DIR/current-issue.json"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROMPT_FILE="$SCRIPT_DIR/prompt.md"

mkdir -p "$RALPH_DIR"

stream_text='select(.type == "text").part.text // empty | gsub("\n"; "\r\n") | . + "\r\n\n"'

# Recebe o número da issue como parâmetro
ISSUE_NUM=$1

if [ -z "$ISSUE_NUM" ]; then
  echo "Usage: $0 <issue-number>"
  exit 1
fi

echo "==> Processing issue #$ISSUE_NUM"

# Baixa dados da issue
gh issue view "$ISSUE_NUM" \
  --repo "$REPO" \
  --json number,title,body,labels \
  > "$ISSUE_FILE"

# Cria ou troca para branch da issue
BRANCH="ralph/issue-$ISSUE_NUM"
git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"

TMPFILE=$(mktemp)
trap "rm -f $TMPFILE" EXIT

# Executa Ralph uma única vez
opencode run \
  --format json \
  --dangerously-skip-permissions \
  "Resolva a issue no arquivo anexado seguindo as instruções do prompt." \
  -f "$PROMPT_FILE" \
  -f "$ISSUE_FILE" \
| tee "$TMPFILE" \
| jq --unbuffered -rj "$stream_text"

FULL_TEXT=$(jq -r 'select(.type == "text").part.text // empty' "$TMPFILE" | tr -d '\n')

# Tratamento de erro
if jq -e 'select(.type == "error")' "$TMPFILE" > /dev/null 2>&1; then
  ERROR=$(jq -r 'select(.type == "error") | .error.data.message // .error.name' "$TMPFILE" | tail -1)

  echo "Agent error: $ERROR"

  git checkout main
  git branch -D "$BRANCH" 2>/dev/null || true

  exit 1
fi

# Issue bloqueada
if [[ "$FULL_TEXT" == *"<promise>BLOCKED:"* ]]; then
  REASON=$(echo "$FULL_TEXT" | grep -oP '(?<=<promise>BLOCKED:).*?(?=</promise>)')

  echo "Issue blocked: $REASON"

  gh issue edit "$ISSUE_NUM" \
    --repo "$REPO" \
    --remove-label "ready-for-agent" \
    --add-label "agent-blocked"

  git checkout main
  git branch -D "$BRANCH" 2>/dev/null || true

  exit 0
fi

# Issue resolvida
if [[ "$FULL_TEXT" == *"<promise>NO MORE TASKS</promise>"* ]]; then
  TITLE=$(gh issue view "$ISSUE_NUM" --repo "$REPO" --json title --jq '.title')

  git add -A

  git commit -m "fix: resolve issue #$ISSUE_NUM

$TITLE

Closes #$ISSUE_NUM"

  git push origin "$BRANCH"

  gh pr create \
    --repo "$REPO" \
    --base main \
    --head "$BRANCH" \
    --title "fix: resolve issue #$ISSUE_NUM" \
    --body "Closes #$ISSUE_NUM

Automated PR generated by Ralph agent."

  echo "PR created successfully."

  exit 0
fi

echo "Issue not completed. No PR created."

git checkout main
git branch -D "$BRANCH" 2>/dev/null || true

exit 1